[workspace]
members = [
    "crates/protocol-types",
    "crates/canonical-encoding",
    "crates/hashing",
    "crates/crypto",
    "crates/commitments",
    "crates/objects",
    "crates/protocol-config",
    "crates/abi",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
protocol-types = { path = "crates/protocol-types" }
canonical-encoding = { path = "crates/canonical-encoding" }
hashing = { path = "crates/hashing" }
crypto = { path = "crates/crypto" }
commitments = { path = "crates/commitments" }
objects = { path = "crates/objects" }
abi = { path = "crates/abi" }
protocol-config = { path = "crates/protocol-config" }
sha2 = "0.10.9"
sha3 = "0.10.8"
