/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0938d568d96cbe8c813b1f6b7c423caf)
interface __BaseEnv_Env {
	NODE_CORE: Fetcher /* sunrise-edge-node-core */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
