[package]
name = "runtime-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
postgres.workspace = true
protocol-types.workspace = true
r2d2_postgres.workspace = true
runtime.workspace = true

[dev-dependencies]
objects.workspace = true
postgres_rustls.workspace = true
rcgen.workspace = true
runtime = { workspace = true, features = ["durable-conformance"] }
rustls.workspace = true
tokio = { workspace = true, features = ["io-util", "sync", "time"] }
