[package]
name = "protocol-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
governance.workspace = true
bonds.workspace = true
canonical-encoding.workspace = true
commitments.workspace = true
consensus.workspace = true
fees.workspace = true
protocol-types.workspace = true
protocol-upgrades.workspace = true
system-modules.workspace = true
