//! The real USB/HID [`Transport`] implementation. This is the only module
//! in this crate — and, by design, in this workspace — that depends on the
//! `hidapi` vendor crate.
//!
//! This module owns two independent layers: the generic USB HID packet
//! framing every Ledger device application uses regardless of which app is
//! installed (fixed 64-byte reports, a channel id, a tag byte, and a
//! big-endian sequence index — completely unrelated to, and one layer below,
//! `SIGNING.md`'s own FIRST/CONTINUE/LAST application-level chunking that
//! [`crate::device::LedgerDevice`] implements), and the thin glue that opens
//! a `hidapi` device and drives that framing.
//!
//! **Unvalidated against physical hardware.** Everything in this module is
//! implemented from documented USB HID/Ledger transport conventions (the
//! vendor id, channel id, and packet size below match the independently
//! published, widely-used Zondax `ledger-go` host library's `ledger_hid.go`;
//! the recognized product-id model family list matches this workspace's own
//! documented S4b five-target build list — Nano X, Nano S Plus, Stax, Flex,
//! and Apex P — see `ARCHITECTURE.md` DR-0091 — with the underlying per-model
//! USB product-id values themselves sourced from Ledger's own current
//! official model data, the `ledger-device-sdk`/`ledger-secure-sdk`
//! device-target definitions and the
//! `@ledgerhq/device-management-kit`/`ledger-live` `StaticDeviceModelDataSource`),
//! not from a test against a
//! real device: physical hardware-in-the-loop evidence is explicitly
//! deferred (see `SIGNING.md`, "Delivery sequence"). The pure framing
//! functions below have both self-consistent round-trip unit tests and
//! independently hand-built byte vectors (not generated by this module's
//! own encoder); neither proves agreement with a real Ledger device's
//! firmware.
//!
//! **Device identity is USB-descriptor-level only.** [`identify_ledger_device`]
//! recognizes a device's USB vendor id, exact HID usage page, and product-id
//! model family. It does not — and cannot, over this transport alone —
//! verify the active on-device application's name/version or the device
//! firmware version. Those live on two different CLAs depending on device
//! context, neither of which this module sends: the active application's
//! name/version is CLA `B0` `INS 01` ("get app and version"); the device
//! firmware version is CLA `E0` `INS 01`, but only while the device is at
//! the dashboard with no application open — a distinct, OS-owned use of the
//! same CLA byte `E0` this workspace's own Sunrise application uses for its
//! signing commands once *it* is the active app (see `SIGNING.md`, "Device
//! APDU contract"). Querying both therefore requires a staged sequence this
//! module does not implement: probe at the dashboard first, then open (or
//! have the operator open) the Sunrise application and reconnect, then send
//! this crate's own `E0` commands. That staged app/firmware identity check
//! is an explicitly separate, not-yet-implemented S4c slice (see
//! `ARCHITECTURE.md` DR-0092); nothing in this module or its tests verifies
//! it, and no caller should treat a successful [`HidTransport::open`] as
//! proof of active-app or firmware identity.

use std::ffi::CString;
use std::fmt;
use std::time::{Duration, Instant};

use hidapi::{DeviceInfo, HidApi, HidDevice};

use crate::apdu::{ApduCommand, ApduResponse, Transport};

/// Ledger's USB vendor id, shared by every Ledger device model.
pub const LEDGER_USB_VENDOR_ID: u16 = 0x2C97;
/// Ledger's dedicated HID usage page for its APDU interface (matches
/// `ledger-go`'s `UsagePageLedgerNanoS`).
///
/// Some host libraries (including `ledger-go`) also accept a device
/// reporting interface number `0` as an alternative to this usage page, to
/// work around platforms that report an empty/zero usage page. This phase
/// does not implement that fallback: without current official primary-source
/// evidence for it, and without a tested, platform-`cfg`-specific policy
/// distinguishing when it is safe to apply, a device reporting an empty or
/// mismatched usage page is treated as unrecognized rather than silently
/// accepted.
const LEDGER_USAGE_PAGE: u16 = 0xFFA0;

/// Fixed USB HID report size Ledger devices use for this framing.
const PACKET_SIZE: usize = 64;
/// Fixed logical channel id.
const CHANNEL_ID: u16 = 0x0101;
/// Fixed packet tag identifying an APDU-carrying frame.
const TAG_APDU: u8 = 0x05;
/// `hid_write`'s leading report-id byte for devices (including Ledger's)
/// that do not use numbered HID reports.
const REPORT_ID_PREFIX: u8 = 0x00;
/// Secondary bound on the number of USB HID packets read for one logical
/// APDU response, independent of [`TOTAL_READ_TIMEOUT`]: with
/// [`MAX_APDU_RESPONSE_LEN`] capping the declared length, a well-formed
/// response never needs more than a handful of packets, so this bound
/// exists only to stop a corrupted stream that keeps reporting "incomplete"
/// from growing `Vec` allocations without limit before the wall-clock
/// deadline below is reached.
const MAX_READ_PACKETS: usize = 8;
/// Bounds the *total* elapsed time reading one logical APDU response,
/// across every USB HID packet it takes to deliver — not a per-packet
/// timeout multiplied by [`MAX_READ_PACKETS`]. A device may legitimately
/// hold the first packet back for a long time while a user reviews an
/// on-device confirmation; a per-packet `hidapi` timeout that elapses with
/// no data is therefore treated as "no data yet" and retried, as long as
/// this overall deadline has not passed.
const TOTAL_READ_TIMEOUT: Duration = Duration::from_secs(30);
/// Maximum accepted short-APDU response *data* length, excluding the
/// trailing two-byte status word.
const MAX_APDU_RESPONSE_DATA_LEN: usize = 258;
/// The short-APDU response maximum this host accepts: up to
/// [`MAX_APDU_RESPONSE_DATA_LEN`] bytes of response data plus the two-byte
/// status word (260 bytes total). Every response this device contract
/// actually returns is far smaller (64 bytes for a signature at most), so
/// this bound exists to reject a corrupted or hostile declared length
/// before it can drive an unbounded read loop or allocation.
const MAX_APDU_RESPONSE_LEN: usize = MAX_APDU_RESPONSE_DATA_LEN + 2;

/// A Ledger device model this crate recognizes by its USB product-id family
/// (the product id's most-significant byte).
///
/// This exact five-model set matches the separate `sunrise-edge-ledger-app`
/// repository's own documented S4b build targets (see `ARCHITECTURE.md`
/// DR-0091: "Nano S+, Nano X, Stax, Flex, and Apex P" — this repository's
/// own record of which models that dedicated Sunrise device application
/// actually builds for). The underlying per-model USB product-id values
/// themselves come from Ledger's own current official model data — the
/// `ledger-device-sdk`/`ledger-secure-sdk` device-target definitions and the
/// `@ledgerhq/device-management-kit`/`ledger-live` `StaticDeviceModelDataSource`
/// — not from this repository. It deliberately excludes the plain Ledger
/// Nano S: no S4b build target covers it, so this host does not recognize
/// it as a valid Sunrise-signing device today.
///
/// This is USB-descriptor-level identity only. It is not the on-device
/// active application name/version or firmware version — see this module's
/// documentation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LedgerProductModel {
    /// Ledger Nano X (`0x40xx`).
    NanoX,
    /// Ledger Nano S Plus (`0x50xx`).
    NanoSPlus,
    /// Ledger Stax (`0x60xx`).
    Stax,
    /// Ledger Flex (`0x70xx`).
    Flex,
    /// Ledger Apex P (`0x80xx`).
    ApexP,
}

impl fmt::Display for LedgerProductModel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::NanoX => "nano-x",
            Self::NanoSPlus => "nano-s-plus",
            Self::Stax => "stax",
            Self::Flex => "flex",
            Self::ApexP => "apex-p",
        })
    }
}

fn classify_product_id(product_id: u16) -> Option<LedgerProductModel> {
    match u8::try_from(product_id >> 8).ok()? {
        0x40 => Some(LedgerProductModel::NanoX),
        0x50 => Some(LedgerProductModel::NanoSPlus),
        0x60 => Some(LedgerProductModel::Stax),
        0x70 => Some(LedgerProductModel::Flex),
        0x80 => Some(LedgerProductModel::ApexP),
        _ => None,
    }
}

/// Pure descriptor-identity check: given raw USB vendor id, product id, and
/// HID usage page values, returns the recognized model or a typed
/// rejection.
///
/// This fails closed on descriptor identity: the caller must report
/// Ledger's vendor id `0x2c97`, a product-id family in the known five-model
/// table, and an exact usage-page match — all three, with no fallback. The
/// interface-number fallback some host libraries (including Zondax's
/// `ledger-go`) use for platforms with an empty/zero usage page is
/// deliberately not applied here (see [`LEDGER_USAGE_PAGE`]'s documentation).
///
/// Taking plain `u16` values rather than `hidapi::DeviceInfo` (which has no
/// public constructor, so it cannot be built in a test) keeps this exact
/// three-field policy directly unit-testable.
fn classify_descriptor(
    vendor_id: u16,
    product_id: u16,
    usage_page: u16,
) -> Result<LedgerProductModel, HidTransportError> {
    if vendor_id != LEDGER_USB_VENDOR_ID {
        return Err(HidTransportError::UnrecognizedVendorId { actual: vendor_id });
    }
    let model = classify_product_id(product_id)
        .ok_or(HidTransportError::UnrecognizedProductModel { product_id })?;
    if usage_page != LEDGER_USAGE_PAGE {
        return Err(HidTransportError::UnrecognizedUsagePage { usage_page });
    }
    Ok(model)
}

/// Identifies `info` as a supported Ledger device, or returns a typed
/// rejection (see [`classify_descriptor`] for the exact policy).
fn identify_ledger_device(info: &DeviceInfo) -> Result<LedgerProductModel, HidTransportError> {
    classify_descriptor(info.vendor_id(), info.product_id(), info.usage_page())
}

/// Errors from the real USB/HID transport.
#[derive(Debug)]
pub enum HidTransportError {
    /// The `hidapi` library reported a failure (enumerate, open, write, or
    /// read).
    Hid(hidapi::HidError),
    /// The supplied device path was not a valid `CStr`.
    InvalidDevicePath,
    /// No currently enumerated HID device has the supplied path.
    DeviceNotFound {
        /// The path that was searched for.
        path: String,
    },
    /// The device at the supplied path reported a USB vendor id other than
    /// [`LEDGER_USB_VENDOR_ID`].
    UnrecognizedVendorId {
        /// Actual reported vendor id.
        actual: u16,
    },
    /// The device's USB product id's most-significant byte is not one of
    /// this crate's known Ledger model families.
    UnrecognizedProductModel {
        /// Actual reported product id.
        product_id: u16,
    },
    /// The device's product id was a known Ledger model family, but its USB
    /// HID usage page did not exactly match [`LEDGER_USAGE_PAGE`].
    UnrecognizedUsagePage {
        /// Actual reported usage page.
        usage_page: u16,
    },
    /// An [`ApduCommand`]'s data exceeded the short-APDU 255-byte limit.
    CommandDataTooLarge {
        /// Actual data length.
        actual: usize,
    },
    /// A USB HID write did not report writing the complete packet.
    ShortWrite {
        /// Expected bytes written (report id byte plus the fixed packet).
        expected: usize,
        /// Actual bytes reported written.
        actual: usize,
    },
    /// A USB HID packet was not read back as exactly [`PACKET_SIZE`] bytes.
    ShortPacket {
        /// Actual bytes read.
        actual: usize,
    },
    /// A received packet's channel id or tag did not match the expected
    /// framing. Fails immediately; never treated as "not enough data yet".
    UnexpectedPacketHeader {
        /// Actual channel id.
        channel: u16,
        /// Actual tag byte.
        tag: u8,
    },
    /// A received packet's sequence index did not match the expected next
    /// value. Fails immediately; never treated as "not enough data yet".
    UnexpectedSequenceIndex {
        /// Expected sequence index.
        expected: u16,
        /// Actual sequence index.
        actual: u16,
    },
    /// The first packet's declared total response length exceeded
    /// [`MAX_APDU_RESPONSE_LEN`]. Fails immediately, before allocating or
    /// reading further packets toward that declared length.
    DeclaredResponseTooLarge {
        /// Actual declared length.
        declared: usize,
        /// Maximum accepted length.
        maximum: usize,
    },
    /// The reconstructed response was shorter than the two-byte status word
    /// it must always end with.
    ResponseTooShortForStatusWord,
    /// More than [`MAX_READ_PACKETS`] packets were read without completing
    /// the declared response length.
    TooManyReadPackets,
    /// [`TOTAL_READ_TIMEOUT`] elapsed before a complete response was
    /// reassembled.
    ReadTimedOut,
    /// An internal framing bound (an arithmetic range this module's own
    /// invariants should always keep within range) was exceeded. This is a
    /// defensive, typed alternative to a panic or a silent
    /// saturating/truncating fallback; it should never actually occur for
    /// any input this module's own callers construct.
    FramingBoundsExceeded,
}

impl fmt::Display for HidTransportError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Hid(error) => write!(f, "hidapi error: {error}"),
            Self::InvalidDevicePath => f.write_str("device path is not a valid CStr"),
            Self::DeviceNotFound { path } => {
                write!(f, "no currently connected HID device has path {path:?}")
            }
            Self::UnrecognizedVendorId { actual } => {
                write!(
                    f,
                    "unrecognized USB vendor id {actual:#06x}, expected {LEDGER_USB_VENDOR_ID:#06x}"
                )
            }
            Self::UnrecognizedProductModel { product_id } => write!(
                f,
                "unrecognized Ledger product id {product_id:#06x}: not a known device model family"
            ),
            Self::UnrecognizedUsagePage { usage_page } => write!(
                f,
                "device did not report the Ledger APDU usage page {LEDGER_USAGE_PAGE:#06x} (got usage_page={usage_page:#06x})"
            ),
            Self::CommandDataTooLarge { actual } => {
                write!(f, "APDU command data is {actual} bytes, maximum is 255")
            }
            Self::ShortWrite { expected, actual } => write!(
                f,
                "USB HID write reported {actual} bytes written, expected exactly {expected}"
            ),
            Self::ShortPacket { actual } => {
                write!(
                    f,
                    "read a {actual}-byte USB HID packet, expected exactly {PACKET_SIZE}"
                )
            }
            Self::UnexpectedPacketHeader { channel, tag } => write!(
                f,
                "received USB HID packet had channel={channel:#06x} tag={tag:#04x}, expected channel={CHANNEL_ID:#06x} tag={TAG_APDU:#04x}"
            ),
            Self::UnexpectedSequenceIndex { expected, actual } => write!(
                f,
                "received USB HID packet sequence index {actual}, expected {expected}"
            ),
            Self::DeclaredResponseTooLarge { declared, maximum } => write!(
                f,
                "device declared a {declared}-byte response, maximum accepted is {maximum}"
            ),
            Self::ResponseTooShortForStatusWord => {
                f.write_str("reconstructed APDU response was shorter than the two-byte status word")
            }
            Self::TooManyReadPackets => {
                write!(
                    f,
                    "exceeded {MAX_READ_PACKETS} USB HID read packets for one APDU response"
                )
            }
            Self::ReadTimedOut => write!(
                f,
                "no complete APDU response was read within {TOTAL_READ_TIMEOUT:?}"
            ),
            Self::FramingBoundsExceeded => f.write_str("internal USB HID framing bound exceeded"),
        }
    }
}

impl std::error::Error for HidTransportError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Hid(error) => Some(error),
            _ => None,
        }
    }
}

/// A real Ledger device reached over USB HID.
pub struct HidTransport {
    device: HidDevice,
    model: LedgerProductModel,
}

impl HidTransport {
    /// Opens the device at the exact platform HID path `path`, requiring it
    /// to first resolve, through `HidApi::device_list`, to a currently
    /// connected device reporting Ledger's USB vendor id, a recognized
    /// product-id model family, and exactly the Ledger APDU usage page (see
    /// [`identify_ledger_device`]) — before this ever calls
    /// `HidApi::open_path`.
    ///
    /// There is no "first device" auto-selection: a caller must name the
    /// exact device explicitly, matching this workspace's existing "no
    /// hidden default" convention (see `apps/cli/src/seed.rs`'s development
    /// seed file). This check is USB-descriptor-level identity only; see
    /// this module's documentation for what it does not verify.
    pub fn open(path: &str) -> Result<Self, HidTransportError> {
        let api = HidApi::new().map_err(HidTransportError::Hid)?;
        let info = api
            .device_list()
            .find(|info| matches!(info.path().to_str(), Ok(candidate) if candidate == path))
            .ok_or_else(|| HidTransportError::DeviceNotFound {
                path: path.to_string(),
            })?;
        let model = identify_ledger_device(info)?;
        let c_path = CString::new(path).map_err(|_| HidTransportError::InvalidDevicePath)?;
        let device = api.open_path(&c_path).map_err(HidTransportError::Hid)?;
        Ok(Self { device, model })
    }

    /// The recognized device model this transport connected to.
    #[must_use]
    pub const fn product_model(&self) -> LedgerProductModel {
        self.model
    }

    /// Lists the platform HID path and recognized model of every currently
    /// connected, recognized Ledger device, for a caller (typically the
    /// CLI) to present to an operator before they select one explicitly.
    /// Devices that fail [`identify_ledger_device`] (for example a
    /// different vendor's device, an unrecognized product model, or a
    /// mismatched usage page) are silently omitted rather than surfaced as
    /// an error, since this is a best-effort discovery listing, not a
    /// strict open.
    pub fn list_devices() -> Result<Vec<(String, LedgerProductModel)>, HidTransportError> {
        let api = HidApi::new().map_err(HidTransportError::Hid)?;
        let mut devices = Vec::new();
        for info in api.device_list() {
            let Ok(model) = identify_ledger_device(info) else {
                continue;
            };
            let Ok(path) = info.path().to_str() else {
                continue;
            };
            devices.push((path.to_string(), model));
        }
        Ok(devices)
    }
}

impl Transport for HidTransport {
    type Error = HidTransportError;

    fn exchange(&mut self, command: &ApduCommand) -> Result<ApduResponse, Self::Error> {
        let raw_command = encode_raw_apdu(command)?;
        write_packets(&self.device, &raw_command)?;
        let raw_response = read_packets(&self.device)?;
        decode_raw_apdu_response(&raw_response)
    }
}

/// Encodes one [`ApduCommand`] as `CLA || INS || P1 || P2 || Lc || data`
/// (the short, single-byte-`Lc` APDU form).
fn encode_raw_apdu(command: &ApduCommand) -> Result<Vec<u8>, HidTransportError> {
    let lc =
        u8::try_from(command.data.len()).map_err(|_| HidTransportError::CommandDataTooLarge {
            actual: command.data.len(),
        })?;
    let mut raw = Vec::with_capacity(5 + command.data.len());
    raw.push(command.cla);
    raw.push(command.ins);
    raw.push(command.p1);
    raw.push(command.p2);
    raw.push(lc);
    raw.extend_from_slice(&command.data);
    Ok(raw)
}

/// Splits `raw_apdu` into the fixed 64-byte USB HID packets Ledger's
/// transport framing uses: `channel_id (2, BE) || tag (1) || seq (2, BE) ||
/// [total_length (2, BE) only on seq 0] || payload`, zero-padded to
/// [`PACKET_SIZE`].
fn encode_hid_packets(raw_apdu: &[u8]) -> Result<Vec<[u8; PACKET_SIZE]>, HidTransportError> {
    let total_length =
        u16::try_from(raw_apdu.len()).map_err(|_| HidTransportError::CommandDataTooLarge {
            actual: raw_apdu.len(),
        })?;
    let mut packets = Vec::new();
    let mut sequence: u16 = 0;
    let mut offset: usize = 0;

    loop {
        let mut packet = [0_u8; PACKET_SIZE];
        packet[0..2].copy_from_slice(&CHANNEL_ID.to_be_bytes());
        packet[2] = TAG_APDU;
        packet[3..5].copy_from_slice(&sequence.to_be_bytes());

        let header_len = if sequence == 0 {
            packet[5..7].copy_from_slice(&total_length.to_be_bytes());
            7
        } else {
            5
        };

        let remaining = raw_apdu
            .len()
            .checked_sub(offset)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        let available = PACKET_SIZE
            .checked_sub(header_len)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        let take = remaining.min(available);
        let end = offset
            .checked_add(take)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        packet[header_len..header_len + take].copy_from_slice(&raw_apdu[offset..end]);
        offset = end;
        packets.push(packet);

        if offset >= raw_apdu.len() {
            break;
        }
        sequence = sequence
            .checked_add(1)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
    }

    Ok(packets)
}

/// The result of feeding one more packet into [`decode_hid_packets`]:
/// either the response is fully reassembled, or more packets are needed.
/// This is deliberately distinct from `Result`'s `Err` arm, which this
/// function reserves for a header/sequence/declared-length problem that
/// must fail the read immediately rather than being treated as "not enough
/// data yet".
#[derive(Debug, PartialEq, Eq)]
enum ReassemblyOutcome {
    /// The declared response length has been fully received.
    Complete(Vec<u8>),
    /// More packets are required to reach the declared response length.
    Incomplete,
}

/// Reassembles the payload carried across a sequence of fixed 64-byte USB
/// HID packets built by [`encode_hid_packets`]'s counterpart on the device
/// side: validates the fixed channel id/tag and strictly increasing
/// sequence index on every packet, and the first packet's declared length
/// against [`MAX_APDU_RESPONSE_LEN`], failing immediately (not returning
/// [`ReassemblyOutcome::Incomplete`]) on any of those mismatches.
fn decode_hid_packets(
    packets: &[[u8; PACKET_SIZE]],
) -> Result<ReassemblyOutcome, HidTransportError> {
    let mut payload = Vec::new();
    let mut declared_len: Option<usize> = None;

    for (index, packet) in packets.iter().enumerate() {
        let channel = u16::from_be_bytes([packet[0], packet[1]]);
        let tag = packet[2];
        if channel != CHANNEL_ID || tag != TAG_APDU {
            return Err(HidTransportError::UnexpectedPacketHeader { channel, tag });
        }
        let sequence = u16::from_be_bytes([packet[3], packet[4]]);
        let expected_sequence =
            u16::try_from(index).map_err(|_| HidTransportError::FramingBoundsExceeded)?;
        if sequence != expected_sequence {
            return Err(HidTransportError::UnexpectedSequenceIndex {
                expected: expected_sequence,
                actual: sequence,
            });
        }

        let (header_len, declared): (usize, usize) = if sequence == 0 {
            let length = u16::from_be_bytes([packet[5], packet[6]]) as usize;
            if length > MAX_APDU_RESPONSE_LEN {
                return Err(HidTransportError::DeclaredResponseTooLarge {
                    declared: length,
                    maximum: MAX_APDU_RESPONSE_LEN,
                });
            }
            declared_len = Some(length);
            (7, length)
        } else {
            match declared_len {
                Some(length) => (5, length),
                // Unreachable: `sequence == 0` is always index 0 (checked
                // above), so `declared_len` is always set before any later
                // iteration reads it. Typed rather than `.expect`/panic.
                None => {
                    return Err(HidTransportError::UnexpectedSequenceIndex {
                        expected: 0,
                        actual: sequence,
                    });
                }
            }
        };

        let remaining_needed = declared
            .checked_sub(payload.len())
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        let available = PACKET_SIZE
            .checked_sub(header_len)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        let take = remaining_needed.min(available);
        let end = header_len
            .checked_add(take)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        payload.extend_from_slice(&packet[header_len..end]);

        if payload.len() >= declared {
            payload.truncate(declared);
            return Ok(ReassemblyOutcome::Complete(payload));
        }
    }

    Ok(ReassemblyOutcome::Incomplete)
}

/// Splits `raw_response` (data followed by a two-byte status word) into an
/// [`ApduResponse`].
fn decode_raw_apdu_response(raw_response: &[u8]) -> Result<ApduResponse, HidTransportError> {
    let split = raw_response
        .len()
        .checked_sub(2)
        .ok_or(HidTransportError::ResponseTooShortForStatusWord)?;
    let status_word = u16::from_be_bytes([raw_response[split], raw_response[split + 1]]);
    Ok(ApduResponse {
        data: raw_response[..split].to_vec(),
        status_word,
    })
}

/// Writes every USB HID packet for `raw_apdu`, requiring each `hid_write`
/// call to report writing the complete `1 + PACKET_SIZE`-byte buffer (the
/// leading report-id byte plus the fixed packet); a short write is a typed
/// [`HidTransportError::ShortWrite`], never silently ignored.
fn write_packets(device: &HidDevice, raw_apdu: &[u8]) -> Result<(), HidTransportError> {
    for packet in encode_hid_packets(raw_apdu)? {
        let mut buffer = Vec::with_capacity(1 + PACKET_SIZE);
        buffer.push(REPORT_ID_PREFIX);
        buffer.extend_from_slice(&packet);
        let written = device.write(&buffer).map_err(HidTransportError::Hid)?;
        if written != buffer.len() {
            return Err(HidTransportError::ShortWrite {
                expected: buffer.len(),
                actual: written,
            });
        }
    }
    Ok(())
}

/// Reads USB HID packets until a complete APDU response is reassembled,
/// bounded by [`TOTAL_READ_TIMEOUT`] total elapsed time (not a per-packet
/// timeout multiplied by [`MAX_READ_PACKETS`]) and, secondarily, by
/// [`MAX_READ_PACKETS`] itself. A header/sequence/declared-length problem
/// from [`decode_hid_packets`] fails immediately via `?`; it is never
/// treated as "keep waiting".
fn read_packets(device: &HidDevice) -> Result<Vec<u8>, HidTransportError> {
    let deadline = Instant::now()
        .checked_add(TOTAL_READ_TIMEOUT)
        .ok_or(HidTransportError::FramingBoundsExceeded)?;
    let mut packets: Vec<[u8; PACKET_SIZE]> = Vec::new();

    loop {
        let now = Instant::now();
        if now >= deadline {
            return Err(HidTransportError::ReadTimedOut);
        }
        if packets.len() >= MAX_READ_PACKETS {
            return Err(HidTransportError::TooManyReadPackets);
        }
        let remaining = deadline
            .checked_duration_since(now)
            .ok_or(HidTransportError::FramingBoundsExceeded)?;
        let timeout_ms = i32::try_from(remaining.as_millis())
            .map_err(|_| HidTransportError::FramingBoundsExceeded)?;

        let mut buffer = [0_u8; PACKET_SIZE];
        let read = device
            .read_timeout(&mut buffer, timeout_ms)
            .map_err(HidTransportError::Hid)?;
        if read == 0 {
            // `hidapi`'s own per-call timeout elapsed with no data; retry
            // until the overall deadline above is reached (see
            // `TOTAL_READ_TIMEOUT`'s documentation for why).
            continue;
        }
        if read != PACKET_SIZE {
            return Err(HidTransportError::ShortPacket { actual: read });
        }
        packets.push(buffer);
        match decode_hid_packets(&packets)? {
            ReassemblyOutcome::Complete(payload) => return Ok(payload),
            ReassemblyOutcome::Incomplete => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_a_payload_that_fits_one_packet() {
        let raw = vec![0xE0, 0x00, 0x00, 0x00, 0x00];
        let packets = encode_hid_packets(&raw).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(
            decode_hid_packets(&packets).unwrap(),
            ReassemblyOutcome::Complete(raw)
        );
    }

    #[test]
    fn round_trips_a_payload_spanning_multiple_packets() {
        let raw: Vec<u8> = (0..200).map(|value| (value % 256) as u8).collect();
        let packets = encode_hid_packets(&raw).unwrap();
        assert!(packets.len() > 1);
        assert_eq!(
            decode_hid_packets(&packets).unwrap(),
            ReassemblyOutcome::Complete(raw)
        );
    }

    #[test]
    fn round_trips_a_payload_at_exactly_the_first_packet_capacity() {
        // First packet capacity is PACKET_SIZE - 7 (channel+tag+seq+length).
        let raw = vec![0xAB_u8; PACKET_SIZE - 7];
        let packets = encode_hid_packets(&raw).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(
            decode_hid_packets(&packets).unwrap(),
            ReassemblyOutcome::Complete(raw)
        );
    }

    #[test]
    fn reports_incomplete_before_the_declared_length_is_fully_received() {
        let raw = vec![0xCD_u8; 200];
        let packets = encode_hid_packets(&raw).unwrap();
        assert!(packets.len() > 1);
        assert_eq!(
            decode_hid_packets(&packets[..1]).unwrap(),
            ReassemblyOutcome::Incomplete
        );
    }

    #[test]
    fn rejects_a_packet_with_the_wrong_channel_or_tag_immediately_not_as_incomplete() {
        let raw = vec![0x01, 0x02, 0x03];
        let mut packets = encode_hid_packets(&raw).unwrap();
        packets[0][2] = 0xFF;
        assert!(matches!(
            decode_hid_packets(&packets),
            Err(HidTransportError::UnexpectedPacketHeader { tag: 0xFF, .. })
        ));
    }

    #[test]
    fn rejects_an_out_of_order_sequence_index_immediately_not_as_incomplete() {
        let raw: Vec<u8> = vec![0xAA_u8; 200];
        let mut packets = encode_hid_packets(&raw).unwrap();
        // Corrupt the second packet's sequence index.
        packets[1][3..5].copy_from_slice(&99_u16.to_be_bytes());
        assert!(matches!(
            decode_hid_packets(&packets),
            Err(HidTransportError::UnexpectedSequenceIndex {
                expected: 1,
                actual: 99
            })
        ));
    }

    #[test]
    fn rejects_a_declared_length_over_the_maximum_before_reading_further() {
        let mut packet = [0_u8; PACKET_SIZE];
        packet[0..2].copy_from_slice(&CHANNEL_ID.to_be_bytes());
        packet[2] = TAG_APDU;
        packet[5..7].copy_from_slice(
            &u16::try_from(MAX_APDU_RESPONSE_LEN + 1)
                .unwrap()
                .to_be_bytes(),
        );
        assert!(matches!(
            decode_hid_packets(&[packet]),
            Err(HidTransportError::DeclaredResponseTooLarge { .. })
        ));
    }

    #[test]
    fn decodes_a_hand_built_single_packet_vector_matching_known_ledger_framing() {
        // Built independently of `encode_hid_packets`, byte-for-byte,
        // matching the documented Ledger HID framing (channel `0x0101`, tag
        // `0x05`, big-endian sequence, 2-byte big-endian length on the
        // first packet) used by Zondax's `ledger-go` (`ledger_hid.go`) and
        // Ledger's own host tooling: a 2-byte payload (`90 00`, a bare
        // success status with no data), zero-padded to the fixed 64-byte
        // report.
        let mut packet = [0_u8; PACKET_SIZE];
        let header_and_payload: [u8; 9] = [0x01, 0x01, 0x05, 0x00, 0x00, 0x00, 0x02, 0x90, 0x00];
        packet[..9].copy_from_slice(&header_and_payload);

        assert_eq!(
            decode_hid_packets(&[packet]).unwrap(),
            ReassemblyOutcome::Complete(vec![0x90, 0x00])
        );
    }

    #[test]
    fn decodes_a_hand_built_two_packet_vector_matching_known_ledger_framing() {
        // A 70-byte payload split across two packets: first packet capacity
        // is 64 - 7 = 57 bytes, second packet capacity is 64 - 5 = 59
        // bytes. Every byte below is computed by hand, not generated by
        // this module's own `encode_hid_packets`.
        let payload: Vec<u8> = (0_u8..70).collect();

        let mut first = [0_u8; PACKET_SIZE];
        first[0] = 0x01;
        first[1] = 0x01;
        first[2] = 0x05;
        first[3] = 0x00;
        first[4] = 0x00;
        first[5] = 0x00;
        first[6] = 0x46; // 70 decimal, big-endian low byte.
        first[7..7 + 57].copy_from_slice(&payload[0..57]);

        let mut second = [0_u8; PACKET_SIZE];
        second[0] = 0x01;
        second[1] = 0x01;
        second[2] = 0x05;
        second[3] = 0x00;
        second[4] = 0x01;
        second[5..5 + 13].copy_from_slice(&payload[57..70]);

        assert_eq!(
            decode_hid_packets(&[first, second]).unwrap(),
            ReassemblyOutcome::Complete(payload)
        );
    }

    #[test]
    fn encode_raw_apdu_rejects_oversized_command_data() {
        let command = ApduCommand {
            cla: 0xE0,
            ins: 0x00,
            p1: 0,
            p2: 0,
            data: vec![0u8; 256],
        };
        assert!(matches!(
            encode_raw_apdu(&command),
            Err(HidTransportError::CommandDataTooLarge { actual: 256 })
        ));
    }

    #[test]
    fn encode_raw_apdu_produces_the_exact_short_apdu_shape() {
        let command = ApduCommand {
            cla: 0xE0,
            ins: 0x04,
            p1: 0x02,
            p2: 0x00,
            data: vec![0xAA, 0xBB],
        };
        let raw = encode_raw_apdu(&command).unwrap();
        assert_eq!(raw, vec![0xE0, 0x04, 0x02, 0x00, 0x02, 0xAA, 0xBB]);
    }

    #[test]
    fn decode_raw_apdu_response_splits_data_and_status_word() {
        let response = decode_raw_apdu_response(&[0x01, 0x02, 0x90, 0x00]).unwrap();
        assert_eq!(response.data, vec![0x01, 0x02]);
        assert_eq!(response.status_word, 0x9000);
    }

    #[test]
    fn decode_raw_apdu_response_accepts_an_empty_data_response() {
        let response = decode_raw_apdu_response(&[0x90, 0x00]).unwrap();
        assert!(response.data.is_empty());
        assert_eq!(response.status_word, 0x9000);
    }

    #[test]
    fn decode_raw_apdu_response_rejects_fewer_than_two_bytes() {
        assert!(matches!(
            decode_raw_apdu_response(&[0x90]),
            Err(HidTransportError::ResponseTooShortForStatusWord)
        ));
    }

    #[test]
    fn identify_ledger_device_classifies_every_s4b_build_target_by_product_id_family() {
        // Matches this workspace's own documented S4b five-target build
        // list exactly (`ARCHITECTURE.md` DR-0091): Nano X, Nano S Plus,
        // Stax, Flex, and Apex P.
        let cases = [
            (0x4001_u16, LedgerProductModel::NanoX),
            (0x5001_u16, LedgerProductModel::NanoSPlus),
            (0x6001_u16, LedgerProductModel::Stax),
            (0x7001_u16, LedgerProductModel::Flex),
            (0x8001_u16, LedgerProductModel::ApexP),
        ];
        for (product_id, expected) in cases {
            assert_eq!(classify_product_id(product_id), Some(expected));
        }
    }

    #[test]
    fn identify_ledger_device_rejects_the_plain_nano_s_product_id_family() {
        // The plain Nano S (`0x10xx`) is not an S4b build target and must
        // not be recognized as a valid Sunrise-signing device.
        assert_eq!(classify_product_id(0x1001), None);
    }

    #[test]
    fn identify_ledger_device_rejects_an_unrecognized_product_id_family() {
        assert_eq!(classify_product_id(0x9901), None);
    }

    #[test]
    fn classify_descriptor_accepts_every_supported_family_at_the_exact_usage_page() {
        let cases = [
            (0x4001_u16, LedgerProductModel::NanoX),
            (0x5001_u16, LedgerProductModel::NanoSPlus),
            (0x6001_u16, LedgerProductModel::Stax),
            (0x7001_u16, LedgerProductModel::Flex),
            (0x8001_u16, LedgerProductModel::ApexP),
        ];
        for (product_id, expected) in cases {
            assert_eq!(
                classify_descriptor(LEDGER_USB_VENDOR_ID, product_id, LEDGER_USAGE_PAGE).unwrap(),
                expected
            );
        }
    }

    #[test]
    fn classify_descriptor_rejects_a_wrong_vendor_id() {
        let error = classify_descriptor(0x1234, 0x4001, LEDGER_USAGE_PAGE).unwrap_err();
        assert!(matches!(
            error,
            HidTransportError::UnrecognizedVendorId { actual: 0x1234 }
        ));
    }

    #[test]
    fn classify_descriptor_rejects_the_plain_nano_s_product_id_family() {
        let error =
            classify_descriptor(LEDGER_USB_VENDOR_ID, 0x1001, LEDGER_USAGE_PAGE).unwrap_err();
        assert!(matches!(
            error,
            HidTransportError::UnrecognizedProductModel { product_id: 0x1001 }
        ));
    }

    #[test]
    fn classify_descriptor_rejects_an_unknown_product_family() {
        let error =
            classify_descriptor(LEDGER_USB_VENDOR_ID, 0x9901, LEDGER_USAGE_PAGE).unwrap_err();
        assert!(matches!(
            error,
            HidTransportError::UnrecognizedProductModel { product_id: 0x9901 }
        ));
    }

    #[test]
    fn classify_descriptor_rejects_usage_page_zero() {
        let error = classify_descriptor(LEDGER_USB_VENDOR_ID, 0x4001, 0x0000).unwrap_err();
        assert!(matches!(
            error,
            HidTransportError::UnrecognizedUsagePage { usage_page: 0x0000 }
        ));
    }

    #[test]
    fn classify_descriptor_rejects_a_wrong_nonzero_usage_page() {
        let error = classify_descriptor(LEDGER_USB_VENDOR_ID, 0x4001, 0x0001).unwrap_err();
        assert!(matches!(
            error,
            HidTransportError::UnrecognizedUsagePage { usage_page: 0x0001 }
        ));
    }
}
