[package]
name = "sunrise-edge-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
abi.workspace = true
crypto.workspace = true
ed25519-zebra.workspace = true
execution.workspace = true
fees.workspace = true
node-core.workspace = true
node-wire.workspace = true
objects.workspace = true
protocol-types.workspace = true

[dev-dependencies]
native-http.workspace = true
protocol-config.workspace = true
sunrise-edge-devnet.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
